using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace TodoApi.Models
{
    /// <summary>
    /// Data Transfer Object for creating a new Todo item.
    /// </summary>
    public class CreateTodoDto
    {
        /// <summary>
        /// The unique identifier for the todo item.
        /// This is generated by the database and ignored during JSON serialization.
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [JsonIgnore]
        public int Id { get; set; }

        /// <summary>
        /// The title or description of the todo task.
        /// Must be between 10 and 1000 characters.
        /// </summary>
        [Required]
        [MinLength(10, ErrorMessage = "Task must be at least 10 characters.")]
        [StringLength(1000, ErrorMessage = "Task cannot exceed 1000 characters.")]
        public string Title { get; set; } = string.Empty;

        /// <summary>
        /// The optional deadline for the todo item.
        /// </summary>
        public DateTime? Deadline { get; set; }

        /// <summary>
        /// Indicates whether the todo item is completed.
        /// Defaults to false.
        /// </summary>
        public bool IsCompleted { get; set; } = false;
    }
}
